### PR TITLE
[Mailbox] Avoid address already in use error

### PR DESCRIPTION
**Pull request by TatianaJin**
Set SO_REUSEADDR for mailbox receiver's socket.

### CODE REVIEW

**Comment by kygx-legend** [comment]
I still don't know the cause. This option just creates a new signature if the former is not cleaned up even the application exits. Right?

**Comment by TatianaJin** [comment]
I am not sure what you mean by signature. SO_REUSEADDR indicates that a socket may bind to the port even if it is held by OS, except when there is an active listening socket bound to the address.

The previous error scenario looks like this: The port is used by a socket in the cluster initiating phase to send information to workers/master, then the socket get closed by destruction, but the OS may hold the port for a little bit longer in case the other side of the connection need some buffered messages. Thus in message receiver, a new socket to bind to the same port may get address already in use error.

**Comment by kygx-legend** [comment]
In terms of destruction, does it mean the Husky cluster is destroyed? The error occurs when starting a new Husky cluster? OS will keep the registration a little longer during this two phases?

**Comment by TatianaJin** [comment]
Not really. For the errors occurring on workers, it is this https://github.com/ddmbr/h4/blob/master/worker/worker.cc#L151 socket that uses some port XXX and get destructed when `InitCluster()` function is returned. The same port XXX is used again in `InitCommEnv()` at https://github.com/ddmbr/h4/blob/master/worker/worker.cc#L169 when constructing the mailbox receiver, where the error occurred according to my previous logs.

I did not address the problem with master though. But I think the case you mention is probable and may cause the same error in master, since the master port is manually set.

**Comment by kygx-legend** [comment]
That's exactly what I want.

**Review by kygx-legend — APPROVED** [review]

**Pull request merged**
