### PR TITLE
[Namespace] Change hb:: to husky::base:: for readability

### PR DESCRIPTION
**Pull request by ddmbr**

### CODE REVIEW

**Review by kygx-legend — APPROVED** [review]

**Comment by kygx-legend** [comment]
Will the dir name 'hb' be changed too? And I think the `include` in unit test file should be modified.

**Comment by ddmbr** [comment]
I'm actually thinking of changing `include/hb/` to `include/` instead, since at the moment we don't have much in this repo. What do you think?

**Comment by ddmbr** [comment]
Or maybe we change `include/hb/` to `include/husky-base/`?

**Comment by kygx-legend** [comment]
When including some `xxx.h`, it is better to recognize where is the `xxx.h`? Adding a dir prefix is better?

**Comment by ddmbr** [comment]
Yes I just realized this, and that's why I think `include/husky-base/` could be better.

**Comment by kygx-legend** [comment]
That's okay. Could you also modify `bin_stream_unittest.cc`?

**Comment by ddmbr** [comment]
Done

**Comment by kygx-legend** [comment]
Will merge then.

**Comment by kygx-legend** [comment]
@ddmbr , I just found that there is a `namespace` branch in this repo. Perhaps you did a wrong pushing?

**Comment by kygx-legend** [comment]
Never mind. Already deleted.

**Pull request merged**
